trigger:
 branches:
   include:
   - staging
    
resources:
  repositories:
  - repository: templates
    type: git
    name: DevopsTools/prodest-build-deploy-templates
    
stages:
- stage: DEV
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  jobs:
  - template: buildOCP.yml@templates
    parameters: 
      namespace: npr-esesp-trilhadeaprendizagem-dev
      app_name: trilhadeaprendizagem
      gitops_repo: https://devops.es.gov.br/DefaultCollection/GESUP/_git/esesp-trilhadeaprendizagem-gitops
      build_context: .
      dockerfile_folder: Trilhas
      group: "esesp-trilhas-dev"

- stage: HOM
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/staging')
  jobs:
  - template: buildOCP.yml@templates
    parameters: 
      namespace: npr-esesp-trilhadeaprendizagem-hom
      app_name: trilhadeaprendizagem
      gitops_repo: https://devops.es.gov.br/DefaultCollection/GESUP/_git/esesp-trilhadeaprendizagem-gitops
      build_context: .
      dockerfile_folder: Trilhas
      group: "esesp-trilhas-hom"

- stage: PROD
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:
  - template: buildOCP.yml@templates
    parameters: 
      namespace: pr-esesp-trilhadeaprendizagem
      app_name: trilhadeaprendizagem
      gitops_repo: https://devops.es.gov.br/DefaultCollection/GESUP/_git/esesp-trilhadeaprendizagem-gitops
      build_context: .
      dockerfile_folder: Trilhas
      group: "esesp-trilhas-prod"
