// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trilhas.Data;

#nullable disable

namespace Trilhas.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.DadosBancarios", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Agencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Banco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContaCorrente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DocenteId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.ToTable("DadosBancarios");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Deficiencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Deficiencias");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Nome = "FÍSICA"
                        },
                        new
                        {
                            Id = 2L,
                            Nome = "AUDITIVA"
                        },
                        new
                        {
                            Id = 3L,
                            Nome = "VISUAL"
                        },
                        new
                        {
                            Id = 4L,
                            Nome = "MENTAL"
                        });
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Docente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Entidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MunicipioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TipoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("TipoId");

                    b.ToTable("Entidades");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Escolaridade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Escolaridades");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Nome = "ALFABETIZADO"
                        },
                        new
                        {
                            Id = 2L,
                            Nome = "ANALFABETO"
                        },
                        new
                        {
                            Id = 3L,
                            Nome = "DOUTOR"
                        },
                        new
                        {
                            Id = 4L,
                            Nome = "MESTRE"
                        },
                        new
                        {
                            Id = 5L,
                            Nome = "PÓS GRADUADO"
                        },
                        new
                        {
                            Id = 6L,
                            Nome = "PRIMEIRO GRAU COMPLETO"
                        },
                        new
                        {
                            Id = 7L,
                            Nome = "PRIMEIRO GRAU INCOMPLETO"
                        },
                        new
                        {
                            Id = 8L,
                            Nome = "SEGUNDO GRAU COMPLETO"
                        },
                        new
                        {
                            Id = 9L,
                            Nome = "SEGUNDO GRAU INCOMPLETO"
                        },
                        new
                        {
                            Id = 10L,
                            Nome = "SUPERIOR COMPLETO"
                        },
                        new
                        {
                            Id = 11L,
                            Nome = "SUPERIOR INCOMPLETO"
                        });
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Formacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<string>("Curso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DocenteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Instituicao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.ToTable("Formacao");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Gestor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("EntidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EntidadeId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Gestores");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Habilitacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("CursoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DocenteId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("DocenteId");

                    b.ToTable("Habilitacao");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Local", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MunicipioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.ToTable("Locais");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.LocalContato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("LocalId")
                        .HasColumnType("bigint");

                    b.Property<string>("NumeroTelefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TipoContatoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.HasIndex("TipoContatoId");

                    b.ToTable("LocalContatos");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.LocalRecurso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("LocalId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<long?>("RecursoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.HasIndex("RecursoId");

                    b.ToTable("LocalRecursos");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.LocalSala", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("LocalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.ToTable("LocalSalas");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Municipio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("NomeMunicipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("codigoMunicipio")
                        .HasColumnType("bigint");

                    b.Property<int>("codigoUf")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Municipios");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            NomeMunicipio = "VITÓRIA",
                            Uf = "ES",
                            codigoMunicipio = 3205309L,
                            codigoUf = 32
                        },
                        new
                        {
                            Id = 2L,
                            NomeMunicipio = "VILA VELHA",
                            Uf = "ES",
                            codigoMunicipio = 3205200L,
                            codigoUf = 32
                        },
                        new
                        {
                            Id = 3L,
                            NomeMunicipio = "SERRA",
                            Uf = "ES",
                            codigoMunicipio = 3205002L,
                            codigoUf = 32
                        },
                        new
                        {
                            Id = 4L,
                            NomeMunicipio = "CARIACICA",
                            Uf = "ES",
                            codigoMunicipio = 3201308L,
                            codigoUf = 32
                        });
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.OrgaoExpedidor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrgaoExpedidor");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Nome = "SECRETARIA DE SEGURANÇA PÚBLICA",
                            Sigla = "SSP"
                        });
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeficienciaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EntidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EscolaridadeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("FlagDeficiente")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MunicipioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroFuncional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIdentidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTitulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OrgaoExpedidorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Pis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SexoId")
                        .HasColumnType("bigint");

                    b.Property<string>("UfIdentidade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeficienciaId");

                    b.HasIndex("EntidadeId");

                    b.HasIndex("EscolaridadeId");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("OrgaoExpedidorId");

                    b.HasIndex("SexoId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.PessoaContato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<long>("TipoPessoaContatoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("TipoPessoaContatoId");

                    b.ToTable("PessoaContato");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Recurso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Custo")
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Sexo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sexo");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Nome = "MASCULINO"
                        },
                        new
                        {
                            Id = 2L,
                            Nome = "FEMININO"
                        },
                        new
                        {
                            Id = 3L,
                            Nome = "OUTRO"
                        });
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.TipoDeEntidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposDeEntidade");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Descricao = "MUNICIPAL"
                        },
                        new
                        {
                            Id = 2L,
                            Descricao = "ESTADUAL"
                        },
                        new
                        {
                            Id = 3L,
                            Descricao = "FEDERAL"
                        },
                        new
                        {
                            Id = 4L,
                            Descricao = "ORGANIZAÇÃO NÃO GOVERNAMENTAL"
                        });
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.TipoLocalContato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoLocalContato");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Nome = "RESIDENCIAL"
                        },
                        new
                        {
                            Id = 2L,
                            Nome = "COMERCIAL"
                        },
                        new
                        {
                            Id = 3L,
                            Nome = "CELULAR"
                        },
                        new
                        {
                            Id = 4L,
                            Nome = "OUTROS"
                        });
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.TipoPessoaContato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoPessoaContato");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Nome = "RESIDENCIAL"
                        },
                        new
                        {
                            Id = 2L,
                            Nome = "COMERCIAL"
                        },
                        new
                        {
                            Id = 3L,
                            Nome = "CELULAR"
                        });
                });

            modelBuilder.Entity("Trilhas.Data.Model.Certificados.Certificado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dados")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Padrao")
                        .HasColumnType("bit");

                    b.Property<int>("TipoCertificado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Certificados");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Certificados.CertificadoEmitido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CodigoAutenticacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("CertificadosEmitidos");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.Evento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("CertificadoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("GEDTHPessoaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CursoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeclaracaoCursistaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeclaracaoDocenteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EntidadeDemandanteId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LimitarInscricoes")
                        .HasColumnType("bit");

                    b.Property<long?>("LocalId")
                        .HasColumnType("bigint");

                    b.Property<string>("MotivoExclusao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlEad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VagasPorEntidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CertificadoId");

                    b.HasIndex("GEDTHPessoaId");

                    b.HasIndex("CursoId");

                    b.HasIndex("DeclaracaoCursistaId");

                    b.HasIndex("DeclaracaoDocenteId");

                    b.HasIndex("EntidadeDemandanteId");

                    b.HasIndex("LocalId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.EventoAgenda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraInscricaoFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraInscricaoInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EventoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Justificativa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroVagas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("EventoAgenda");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.EventoCota", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("EntidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EventoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntidadeId");

                    b.HasIndex("EventoId");

                    b.ToTable("EventoCota");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.EventoHorario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DocenteId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EventoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FuncaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LocalSalaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModuloId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.HasIndex("EventoId");

                    b.HasIndex("FuncaoId");

                    b.HasIndex("LocalSalaId");

                    b.HasIndex("ModuloId");

                    b.ToTable("EventoHorario");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.EventoRecurso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("EventoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<long?>("RecursoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("RecursoId");

                    b.ToTable("EventoRecurso");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.FuncaoDocente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FuncoesDocente");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Descricao = "DOCENTE"
                        },
                        new
                        {
                            Id = 2L,
                            Descricao = "DOCENTE ASSISTENTE"
                        },
                        new
                        {
                            Id = 3L,
                            Descricao = "CONFERENCISTA"
                        },
                        new
                        {
                            Id = 4L,
                            Descricao = "PALESTRANTE"
                        },
                        new
                        {
                            Id = 5L,
                            Descricao = "PAINELISTA"
                        },
                        new
                        {
                            Id = 6L,
                            Descricao = "DEBATEDOR"
                        },
                        new
                        {
                            Id = 7L,
                            Descricao = "MODERADOR"
                        });
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.Inscrito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataDeInscricao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Frequencia")
                        .HasColumnType("float");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ListaDeInscricaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PenalidadeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ListaDeInscricaoId");

                    b.HasIndex("PenalidadeId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Inscritos");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.ListaDeInscricao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EventoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventoId")
                        .IsUnique()
                        .HasFilter("[EventoId] IS NOT NULL");

                    b.ToTable("ListaDeInscricao");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.Penalidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DataDaPenalidade")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFimPenalidade")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicioPenalidade")
                        .HasColumnType("datetime2");

                    b.Property<string>("JustificativaDeCancelamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("Penalidades");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.RegistroDePresenca", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("EventoHorarioId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Presente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EventoHorarioId");

                    b.HasIndex("PessoaId");

                    b.ToTable("RegistrosDePresenca");
                });

            modelBuilder.Entity("Trilhas.Data.Model.TermosReferencia.TermoDeReferencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("CaminhoArquivoOriginal")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("TermosDeReferencia");
                });

            modelBuilder.Entity("Trilhas.Data.Model.TermosReferencia.TermoReferenciaItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("AlunosPorTurma")
                        .HasColumnType("int");

                    b.Property<decimal>("CargaHoraria")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DataOferta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EncargosPercentual")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MesExecucao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modalidade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Profissional")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeTurmas")
                        .HasColumnType("int");

                    b.Property<long>("TermoDeReferenciaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TermoDeReferenciaId");

                    b.ToTable("TermoReferenciaItens");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.Eixo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Eixos");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.Estacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EixoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EixoId");

                    b.ToTable("Estacoes");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.Habilidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("CursoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.ItemDaTrilha", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SolucaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TrilhaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SolucaoId");

                    b.HasIndex("TrilhaId");

                    b.ToTable("ItensDaTrilha");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.Modulo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<long?>("CursoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.NivelDeCurso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NiveisDeCurso");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Descricao = "CAPACITAÇÃO"
                        },
                        new
                        {
                            Id = 2L,
                            Descricao = "FORMAÇÃO"
                        });
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.SolucaoEducacional", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EstacaoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDeSolucao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstacaoId");

                    b.ToTable("SolucoesEducacionais");

                    b.HasDiscriminator<string>("TipoDeSolucao").HasValue("SolucaoEducacional");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.TipoDeCurso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposDeCurso");

                    b.HasData(
                        new
                        {
                            Id = 5L,
                            Descricao = "FÓRUM"
                        },
                        new
                        {
                            Id = 7L,
                            Descricao = "MESA REDONDA"
                        },
                        new
                        {
                            Id = 9L,
                            Descricao = "PALESTRA"
                        },
                        new
                        {
                            Id = 11L,
                            Descricao = "SEMINÁRIO"
                        },
                        new
                        {
                            Id = 13L,
                            Descricao = "WORKSHOP"
                        });
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.TrilhaDoUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trilhas");
                });

            modelBuilder.Entity("Trilhas.SqlDto.GridCursistaDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeEvento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GridCursistaDto");
                });

            modelBuilder.Entity("Trilhas.SqlDto.GridDocenteDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CargaHorariaTotal")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Excluido")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeEvento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GridDocenteDto");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.Curso", b =>
                {
                    b.HasBaseType("Trilhas.Data.Model.Trilhas.SolucaoEducacional");

                    b.Property<string>("ConteudoProgramatico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FrequenciaMinimaCertificado")
                        .HasColumnType("int");

                    b.Property<int>("FrequenciaMinimaDeclaracao")
                        .HasColumnType("int");

                    b.Property<int>("Modalidade")
                        .HasColumnType("int");

                    b.Property<long?>("NivelDoCursoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("PermiteCertificado")
                        .HasColumnType("bit");

                    b.Property<string>("PreRequisitos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicoAlvo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TipoDoCursoId")
                        .HasColumnType("bigint");

                    b.HasIndex("NivelDoCursoId");

                    b.HasIndex("TipoDoCursoId");

                    b.HasDiscriminator().HasValue("curso");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.Livro", b =>
                {
                    b.HasBaseType("Trilhas.Data.Model.Trilhas.SolucaoEducacional");

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Edicao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Editora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutrasInformacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("livro");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.Video", b =>
                {
                    b.HasBaseType("Trilhas.Data.Model.Trilhas.SolucaoEducacional");

                    b.Property<DateTime?>("DataProducao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutrasInformacoes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Video_OutrasInformacoes");

                    b.Property<string>("Responsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Video_Url");

                    b.HasDiscriminator().HasValue("video");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.DadosBancarios", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Cadastro.Docente", "Docente")
                        .WithMany("DadosBancarios")
                        .HasForeignKey("DocenteId");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Docente", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Cadastro.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Entidade", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Cadastro.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId");

                    b.HasOne("Trilhas.Data.Model.Cadastro.TipoDeEntidade", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Formacao", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Cadastro.Docente", "Docente")
                        .WithMany("Formacao")
                        .HasForeignKey("DocenteId");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Gestor", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Cadastro.Entidade", "Entidade")
                        .WithMany("Gestores")
                        .HasForeignKey("EntidadeId");

                    b.HasOne("Trilhas.Data.Model.Cadastro.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId");

                    b.Navigation("Entidade");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Habilitacao", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Trilhas.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId");

                    b.HasOne("Trilhas.Data.Model.Cadastro.Docente", "Docente")
                        .WithMany("Habilitacao")
                        .HasForeignKey("DocenteId");

                    b.Navigation("Curso");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Local", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Cadastro.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.LocalContato", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Cadastro.Local", "Local")
                        .WithMany("Contatos")
                        .HasForeignKey("LocalId");

                    b.HasOne("Trilhas.Data.Model.Cadastro.TipoLocalContato", "TipoContato")
                        .WithMany()
                        .HasForeignKey("TipoContatoId");

                    b.Navigation("Local");

                    b.Navigation("TipoContato");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.LocalRecurso", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Cadastro.Local", "Local")
                        .WithMany("Recursos")
                        .HasForeignKey("LocalId");

                    b.HasOne("Trilhas.Data.Model.Cadastro.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId");

                    b.Navigation("Local");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.LocalSala", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Cadastro.Local", "Local")
                        .WithMany("Salas")
                        .HasForeignKey("LocalId");

                    b.Navigation("Local");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Pessoa", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Cadastro.Deficiencia", "Deficiencia")
                        .WithMany()
                        .HasForeignKey("DeficienciaId");

                    b.HasOne("Trilhas.Data.Model.Cadastro.Entidade", "Entidade")
                        .WithMany()
                        .HasForeignKey("EntidadeId");

                    b.HasOne("Trilhas.Data.Model.Cadastro.Escolaridade", "Escolaridade")
                        .WithMany()
                        .HasForeignKey("EscolaridadeId");

                    b.HasOne("Trilhas.Data.Model.Cadastro.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId");

                    b.HasOne("Trilhas.Data.Model.Cadastro.OrgaoExpedidor", "OrgaoExpedidorIdentidade")
                        .WithMany()
                        .HasForeignKey("OrgaoExpedidorId");

                    b.HasOne("Trilhas.Data.Model.Cadastro.Sexo", "Sexo")
                        .WithMany()
                        .HasForeignKey("SexoId");

                    b.Navigation("Deficiencia");

                    b.Navigation("Entidade");

                    b.Navigation("Escolaridade");

                    b.Navigation("Municipio");

                    b.Navigation("OrgaoExpedidorIdentidade");

                    b.Navigation("Sexo");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.PessoaContato", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Cadastro.Pessoa", "Pessoa")
                        .WithMany("Contatos")
                        .HasForeignKey("PessoaId");

                    b.HasOne("Trilhas.Data.Model.Cadastro.TipoPessoaContato", "TipoPessoaContato")
                        .WithMany()
                        .HasForeignKey("TipoPessoaContatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("TipoPessoaContato");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Certificados.CertificadoEmitido", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Cadastro.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.Evento", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Certificados.Certificado", "Certificado")
                        .WithMany()
                        .HasForeignKey("CertificadoId");

                    b.HasOne("Trilhas.Data.Model.Cadastro.Pessoa", "GEDTH")
                        .WithMany()
                        .HasForeignKey("GEDTHPessoaId");

                    b.HasOne("Trilhas.Data.Model.Trilhas.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId");

                    b.HasOne("Trilhas.Data.Model.Certificados.Certificado", "DeclaracaoCursista")
                        .WithMany()
                        .HasForeignKey("DeclaracaoCursistaId");

                    b.HasOne("Trilhas.Data.Model.Certificados.Certificado", "DeclaracaoDocente")
                        .WithMany()
                        .HasForeignKey("DeclaracaoDocenteId");

                    b.HasOne("Trilhas.Data.Model.Cadastro.Entidade", "EntidadeDemandante")
                        .WithMany()
                        .HasForeignKey("EntidadeDemandanteId");

                    b.HasOne("Trilhas.Data.Model.Cadastro.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId");

                    b.Navigation("Certificado");

                    b.Navigation("GEDTH");

                    b.Navigation("Curso");

                    b.Navigation("DeclaracaoCursista");

                    b.Navigation("DeclaracaoDocente");

                    b.Navigation("EntidadeDemandante");

                    b.Navigation("Local");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.EventoAgenda", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Eventos.Evento", "Evento")
                        .WithMany("Agendas")
                        .HasForeignKey("EventoId");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.EventoCota", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Cadastro.Entidade", "Entidade")
                        .WithMany()
                        .HasForeignKey("EntidadeId");

                    b.HasOne("Trilhas.Data.Model.Eventos.Evento", "Evento")
                        .WithMany("Cotas")
                        .HasForeignKey("EventoId");

                    b.Navigation("Entidade");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.EventoHorario", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Cadastro.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId");

                    b.HasOne("Trilhas.Data.Model.Eventos.Evento", "Evento")
                        .WithMany("Horarios")
                        .HasForeignKey("EventoId");

                    b.HasOne("Trilhas.Data.Model.Eventos.FuncaoDocente", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoId");

                    b.HasOne("Trilhas.Data.Model.Cadastro.LocalSala", "Sala")
                        .WithMany()
                        .HasForeignKey("LocalSalaId");

                    b.HasOne("Trilhas.Data.Model.Trilhas.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId");

                    b.Navigation("Docente");

                    b.Navigation("Evento");

                    b.Navigation("Funcao");

                    b.Navigation("Modulo");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.EventoRecurso", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Eventos.Evento", "Evento")
                        .WithMany("Recursos")
                        .HasForeignKey("EventoId");

                    b.HasOne("Trilhas.Data.Model.Cadastro.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId");

                    b.Navigation("Evento");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.Inscrito", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Eventos.ListaDeInscricao", "ListaDeInscricao")
                        .WithMany("Inscritos")
                        .HasForeignKey("ListaDeInscricaoId");

                    b.HasOne("Trilhas.Data.Model.Eventos.Penalidade", "Penalidade")
                        .WithMany()
                        .HasForeignKey("PenalidadeId");

                    b.HasOne("Trilhas.Data.Model.Cadastro.Pessoa", "Cursista")
                        .WithMany()
                        .HasForeignKey("PessoaId");

                    b.Navigation("Cursista");

                    b.Navigation("ListaDeInscricao");

                    b.Navigation("Penalidade");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.ListaDeInscricao", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Eventos.Evento", "Evento")
                        .WithOne("ListaDeInscricao")
                        .HasForeignKey("Trilhas.Data.Model.Eventos.ListaDeInscricao", "EventoId");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.Penalidade", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Cadastro.Pessoa", "Cursista")
                        .WithMany()
                        .HasForeignKey("PessoaId");

                    b.Navigation("Cursista");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.RegistroDePresenca", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Eventos.EventoHorario", "EventoHorario")
                        .WithMany("ListaDePresenca")
                        .HasForeignKey("EventoHorarioId");

                    b.HasOne("Trilhas.Data.Model.Cadastro.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId");

                    b.Navigation("EventoHorario");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Trilhas.Data.Model.TermosReferencia.TermoReferenciaItem", b =>
                {
                    b.HasOne("Trilhas.Data.Model.TermosReferencia.TermoDeReferencia", "TermoDeReferencia")
                        .WithMany("Itens")
                        .HasForeignKey("TermoDeReferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TermoDeReferencia");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.Estacao", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Trilhas.Eixo", "Eixo")
                        .WithMany()
                        .HasForeignKey("EixoId");

                    b.Navigation("Eixo");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.Habilidade", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Trilhas.Curso", "Curso")
                        .WithMany("Habilidades")
                        .HasForeignKey("CursoId");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.ItemDaTrilha", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Trilhas.SolucaoEducacional", "SolucaoEducacional")
                        .WithMany()
                        .HasForeignKey("SolucaoId");

                    b.HasOne("Trilhas.Data.Model.Trilhas.TrilhaDoUsuario", "Trilha")
                        .WithMany("Itens")
                        .HasForeignKey("TrilhaId");

                    b.Navigation("SolucaoEducacional");

                    b.Navigation("Trilha");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.Modulo", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Trilhas.Curso", "Curso")
                        .WithMany("Modulos")
                        .HasForeignKey("CursoId");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.SolucaoEducacional", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Trilhas.Estacao", "Estacao")
                        .WithMany()
                        .HasForeignKey("EstacaoId");

                    b.Navigation("Estacao");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.Curso", b =>
                {
                    b.HasOne("Trilhas.Data.Model.Trilhas.NivelDeCurso", "NivelDoCurso")
                        .WithMany()
                        .HasForeignKey("NivelDoCursoId");

                    b.HasOne("Trilhas.Data.Model.Trilhas.TipoDeCurso", "TipoDoCurso")
                        .WithMany()
                        .HasForeignKey("TipoDoCursoId");

                    b.Navigation("NivelDoCurso");

                    b.Navigation("TipoDoCurso");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Docente", b =>
                {
                    b.Navigation("DadosBancarios");

                    b.Navigation("Formacao");

                    b.Navigation("Habilitacao");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Entidade", b =>
                {
                    b.Navigation("Gestores");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Local", b =>
                {
                    b.Navigation("Contatos");

                    b.Navigation("Recursos");

                    b.Navigation("Salas");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Cadastro.Pessoa", b =>
                {
                    b.Navigation("Contatos");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.Evento", b =>
                {
                    b.Navigation("Agendas");

                    b.Navigation("Cotas");

                    b.Navigation("Horarios");

                    b.Navigation("ListaDeInscricao");

                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.EventoHorario", b =>
                {
                    b.Navigation("ListaDePresenca");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Eventos.ListaDeInscricao", b =>
                {
                    b.Navigation("Inscritos");
                });

            modelBuilder.Entity("Trilhas.Data.Model.TermosReferencia.TermoDeReferencia", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.TrilhaDoUsuario", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Trilhas.Data.Model.Trilhas.Curso", b =>
                {
                    b.Navigation("Habilidades");

                    b.Navigation("Modulos");
                });
#pragma warning restore 612, 618
        }
    }
}
